input_file_path: "/Users/luiskremer/Code/Uni/Code_Master_RSIV/019_scanline_segmentation/data/03_labeled/SiteB_Scans_Global_I_RGB_RHV/SiteB_RHV_03_Labeled.txt"
output_dir: "/Users/luiskremer/Code/Uni/Code_Master_RSIV/019_scanline_segmentation/data/07_classification/3d_classification/test"
model_path: "..."

nghb_search_radius: 0.25
voxel_size: 0.03

classification: False
save_cls_result: False

sampling:
  attributes_path: "/Users/luiskremer/Code/Uni/Code_Master_RSIV/019_scanline_segmentation/data/07_classification/3d_classification/radius50cm_voxel5cm/column_names/column_names.pkl"
  files_dir: "/Users/luiskremer/Code/Uni/Code_Master_RSIV/019_scanline_segmentation/data/07_classification/3d_classification/radius50cm_voxel5cm/attributes/validation"

evaluation:
  output_dir: "/Users/luiskremer/Code/Uni/Code_Master_RSIV/019_scanline_segmentation/data/07_classification/3d_classification/radius50cm_voxel5cm/classification_result/3d_2d_comparison"
  testing_3d: "/Users/luiskremer/Code/Uni/Code_Master_RSIV/019_scanline_segmentation/data/07_classification/3d_classification/radius50cm_voxel5cm/classification_result/classified_pcd/testing"
  testing_2d: "/Users/luiskremer/Code/Uni/Code_Master_RSIV/019_scanline_segmentation/data/07_classification/2d_classification/classified_pcd/testing"
  validation_3d: "/Users/luiskremer/Code/Uni/Code_Master_RSIV/019_scanline_segmentation/data/07_classification/3d_classification/radius50cm_voxel5cm/classification_result/classified_pcd/validation"
  validation_2d: "/Users/luiskremer/Code/Uni/Code_Master_RSIV/019_scanline_segmentation/data/07_classification/2d_classification/classified_pcd/validation"