defaults:
  - _self_

pcd_path: data/01_raw/SiteA_Scans_Global_I_RGB_RHV/SiteA_RHV_01.asc

pcd_col:
  x: 0
  y: 1
  z: 2
  intensity: 3
  red: 4
  green: 5
  blue: 6
  rho: 7 
  horiz_angle: 8
  vert_angle: 9
  expected_value: 10
  scanline_id: 11
  rho_diff: 12
  slope: 13
  curvature: 14
  nx: 15
  ny: 16
  nz: 17
  segment_ids: 18

sce:
  threshold: 100
  bin_size: 0.5
  fmt: "%1.4f %1.4f %1.4f %1.6f %u %u %u %1.4f %1.6f %1.6f %1.6f %u"
  save_pcd: True

scs:
  expected_value_factor: 50
  slope_threshold: 0.25
  curvature_threshold: 45
  fmt:  "%1.4f %1.4f %1.4f %1.6f %u %u %u %1.4f %1.6f %1.6f %1.6f %u %1.6f %1.6f %1.6f %1.4f %1.4f %1.4f %u"
  save_pcd: False

scsb:
  fmt:  "%1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %u %u %u %1.4f %1.4f %1.4f %u %u %u %1.4f %1.4f %1.4f %u %u %u %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f %1.4f"
  save_pcd: False


