defaults:
  - _self_

pcd_path: data/03_labeled/SiteD_Scans_Global_I_RGB_RHV/SiteD_RHV_01_Labeled.txt

attributes: ["intensity","red","green","blue","rho","slope","curvature","roughness","nx_xyz","ny_xyz","nz_xyz"]
#attributes: ["intensity","red","green","blue","rho","slope","curvature","roughness","nx_xyz","ny_xyz","nz_xyz","nx","ny","nz"]
#attributes: ["intensity","rho","slope","curvature","nx_xyz","ny_xyz","nz_xyz","nx","ny","nz"]

sce:
  threshold: 100
  bin_size: 0.5
  k_nn: 16
  z_offset: 30
  relocate_origin: False
  calculate_normals: False
  save_pcd: False

scs:
  #expected_value_factor: 50
  slope_threshold: 0.25
  curvature_threshold: 30
  std_multiplier: 100
  least_squares_method: True
  save_pcd: False

scsb:
  save_pcd: True

pcd_col:
  x: 0
  y: 1
  z: 2
  intensity: 3
  red: 4
  green: 5
  blue: 6
  rho: 7 
  horiz_angle: 8
  vert_angle: 9
  point_counter: 10
  label: 11
  expected_value: 12
  expected_value_std: 13
  scanline_id: 14
  rho_diff: 15
  slope: 16
  curvature: 17
  roughness: 18
  segment_ids: 19
  nx_xyz: 20
  ny_xyz: 21
  nz_xyz: 22
  nx: 23
  ny: 24
  nz: 25

pcd_col_fmt:
  x: "%1.4f"
  y: "%1.4f"
  z: "%1.4f"
  intensity: "%1.6f"
  red: "%u"
  green: "%u"
  blue: "%u"
  rho: "%1.4f"
  horiz_angle: "%1.6f"
  vert_angle: "%1.6f"
  point_counter: "%u"
  label: "%uf"
  expected_value: "%1.4f"
  expected_value_std: "%1.4f"
  scanline_id: "%u"
  rho_diff: "%1.4f"
  slope: "%1.4f"
  curvature: "%1.4f"
  roughness: "%1.8f"
  segment_ids: "%1.4f"
  nx_xyz: "%1.4f"
  ny_xyz: "%1.4f"
  nz_xyz: "%1.4f"
  nx: "%1.4f"
  ny: "%1.4f"
  nz: "%1.4f"

# Fixed statistics (changing the variables will not affect the output; keep the values as they are)
statistics: ["mean","var","std","median","perc2nd","perc98th","skewness"]

# Fixed attributes
xyz_attributes: ["x_median_nn","y_median_nn","z_median_nn","x_perc2nd_nn","y_perc2nd_nn","z_perc2nd_nn","x_perc98th_nn","y_perc98th_nn","z_perc98th_nn"] 











