defaults:
  - _self_
  - a01_curvature: ../analysis/a01_curvature
  - training: ../training
  - attribute: ../attributes
  - paths: ../paths
  - cls_3d: ../3d_cls

# Path where the point cloud is stored
pcd_path: data/03_labeled/SiteD_Scans_Global_I_RGB_RHV/SiteD_RHV_01_Labeled.txt

# Path for saving the output of the module
dst_dir: /Users/luiskremer/Code/Uni/Code_Master_RSIV/019_scanline_segmentation/data/test_output3

# Compression of the output point clouds (True: .npz-files, False: .txt-files)
# Compression needs more time but less space 
output_compressed: False 

# Attributes to be calculated that are taken into account for training the random forest model
#attributes: ["intensity","red","green","blue","rho","slope","curvature","roughness","nx_xyz","ny_xyz","nz_xyz"]
#attributes: ["z","intensity","red","green","blue","rho","vert_angle","slope","curvature","roughness","nx_xyz","ny_xyz","nz_xyz","nx","ny","nz"]
#attributes: ["intensity","red","green","blue","vert_angle","slope","curvature","roughness","nz"]
attributes: ["z","red","green","vert_angle","slope","curvature","roughness"] #"nx","ny","nz"

# Scanline extraction
sce:
  # Threshold (deg) value for splitting the scanlines (in relation to the vertical movement of the scanner)
  threshold: 80
  # Whether or not the point cloud should be saved after this intermediate processing step
  save_pcd: False

# Segmentation
scs:
  curvature_threshold: 5
  std_multiplier: 10
  scanline_3D_attributes: False
  save_pcd: False

# Subsampling
scsb:
  save_pcd: True
  save_gini_impurity: False

# Segment classification
sgcl:
  save_pcd: False

# Whether to run the classification or not
run_classification: False

# Whether to clear the logs or not
clear_logs: False

# Fixed structure of the point cloud columns (don't change)
pcd_col:
  x: 0
  y: 1
  z: 2
  intensity: 3
  red: 4
  green: 5
  blue: 6
  rho: 7 
  horiz_angle: 8
  vert_angle: 9
  point_counter: 10
  label: 11
  scanline_id: 12
  segment_ids: 13
  rho_diff: 14
  slope: 15
  curvature: 16
  roughness: 17
  curvature_scanline_3D: 18
  zenith_angle_scanline_3D: 19

# Point cloud data column format 
# np.savetxt fmt argument is set to '%.18e' by default, resulting in large files
pcd_col_fmt:
  x: "%1.4f"
  y: "%1.4f"
  z: "%1.4f"
  intensity: "%1.6f"
  red: "%u"
  green: "%u"
  blue: "%u"
  rho: "%1.4f"
  horiz_angle: "%1.6f"
  vert_angle: "%1.6f"
  point_counter: "%u"
  label: "%u"
  scanline_id: "%u"
  segment_ids: "%u"
  rho_diff: "%1.4f"
  slope: "%1.4f"
  curvature: "%1.4f"
  roughness: "%1.8f"
  curvature_scanline_3D: "%1.4f"
  zenith_angle_scanline_3D: "%1.4f"

# Fixed statistics (changing the variables will not affect the output; keep the values as they are)
statistics: ["mean","var","std","median","perc2nd","perc98th","perc25th","perc75th","skewness"]
#statistics: ["std","perc2nd","perc98th","perc25th","perc75th","skewness"]

# Fixed attributes
xyz_attributes: ["x_median_nn","y_median_nn","z_median_nn","x_perc2nd_nn","y_perc2nd_nn","z_perc2nd_nn","x_perc98th_nn","y_perc98th_nn","z_perc98th_nn"] 

# Will be filled in the script
filename: None









