rf_model: data/models/random_forest_98features.joblib

segcl:
  output_dir_pcd_classified: data/07_classification
  output_dir_metrics: data/07_classification/results_metrics
  output_dir_cnfmat: data/07_classification/results_confusion_matrix